import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database with countries...');
  const countriesData = [
    { name: 'Afghanistan', isoCode: 'AF' },
    { name: 'Albania', isoCode: 'AL' },
    { name: 'Algeria', isoCode: 'DZ' },
    { name: 'American Samoa', isoCode: 'AS' },
    { name: 'Andorra', isoCode: 'AD' },
    { name: 'Angola', isoCode: 'AO' },
    { name: 'Anguilla', isoCode: 'AI' },
    { name: 'Antarctica', isoCode: 'AQ' },
    { name: 'Antigua and Barbuda', isoCode: 'AG' },
    { name: 'Argentina', isoCode: 'AR' },
    { name: 'Armenia', isoCode: 'AM' },
    { name: 'Aruba', isoCode: 'AW' },
    { name: 'Australia', isoCode: 'AU' },
    { name: 'Austria', isoCode: 'AT' },
    { name: 'Azerbaijan', isoCode: 'AZ' },
    { name: 'Bahamas', isoCode: 'BS' },
    { name: 'Bahrain', isoCode: 'BH' },
    { name: 'Bangladesh', isoCode: 'BD' },
    { name: 'Barbados', isoCode: 'BB' },
    { name: 'Belarus', isoCode: 'BY' },
    { name: 'Belgium', isoCode: 'BE' },
    { name: 'Belize', isoCode: 'BZ' },
    { name: 'Benin', isoCode: 'BJ' },
    { name: 'Bermuda', isoCode: 'BM' },
    { name: 'Bhutan', isoCode: 'BT' },
    { name: 'Bolivia', isoCode: 'BO' },
    { name: 'Bosnia and Herzegovina', isoCode: 'BA' },
    { name: 'Botswana', isoCode: 'BW' },
    { name: 'Brazil', isoCode: 'BR' },
    { name: 'British Indian Ocean Territory', isoCode: 'IO' },
    { name: 'British Virgin Islands', isoCode: 'VG' },
    { name: 'Brunei', isoCode: 'BN' },
    { name: 'Bulgaria', isoCode: 'BG' },
    { name: 'Burkina Faso', isoCode: 'BF' },
    { name: 'Burundi', isoCode: 'BI' },
    { name: 'Cambodia', isoCode: 'KH' },
    { name: 'Cameroon', isoCode: 'CM' },
    { name: 'Canada', isoCode: 'CA' },
    { name: 'Cape Verde', isoCode: 'CV' },
    { name: 'Cayman Islands', isoCode: 'KY' },
    { name: 'Central African Republic', isoCode: 'CF' },
    { name: 'Chad', isoCode: 'TD' },
    { name: 'Chile', isoCode: 'CL' },
    { name: 'China', isoCode: 'CN' },
    { name: 'Christmas Island', isoCode: 'CX' },
    { name: 'Cocos (Keeling) Islands', isoCode: 'CC' },
    { name: 'Colombia', isoCode: 'CO' },
    { name: 'Comoros', isoCode: 'KM' },
    { name: 'Congo (Brazzaville)', isoCode: 'CG' },
    { name: 'Congo (Kinshasa)', isoCode: 'CD' },
    { name: 'Cook Islands', isoCode: 'CK' },
    { name: 'Costa Rica', isoCode: 'CR' },
    { name: 'Croatia', isoCode: 'HR' },
    { name: 'Cuba', isoCode: 'CU' },
    { name: 'Curacao', isoCode: 'CW' },
    { name: 'Cyprus', isoCode: 'CY' },
    { name: 'Czech Republic', isoCode: 'CZ' },
    { name: 'Denmark', isoCode: 'DK' },
    { name: 'Djibouti', isoCode: 'DJ' },
    { name: 'Dominica', isoCode: 'DM' },
    { name: 'Dominican Republic', isoCode: 'DO' },
    { name: 'Ecuador', isoCode: 'EC' },
    { name: 'Egypt', isoCode: 'EG' },
    { name: 'El Salvador', isoCode: 'SV' },
    { name: 'Equatorial Guinea', isoCode: 'GQ' },
    { name: 'Eritrea', isoCode: 'ER' },
    { name: 'Estonia', isoCode: 'EE' },
    { name: 'Eswatini', isoCode: 'SZ' },
    { name: 'Ethiopia', isoCode: 'ET' },
    { name: 'Falkland Islands', isoCode: 'FK' },
    { name: 'Faroe Islands', isoCode: 'FO' },
    { name: 'Fiji', isoCode: 'FJ' },
    { name: 'Finland', isoCode: 'FI' },
    { name: 'France', isoCode: 'FR' },
    { name: 'French Guiana', isoCode: 'GF' },
    { name: 'French Polynesia', isoCode: 'PF' },
    { name: 'French Southern Territories', isoCode: 'TF' },
    { name: 'Gabon', isoCode: 'GA' },
    { name: 'Gambia', isoCode: 'GM' },
    { name: 'Georgia', isoCode: 'GE' },
    { name: 'Germany', isoCode: 'DE' },
    { name: 'Ghana', isoCode: 'GH' },
    { name: 'Gibraltar', isoCode: 'GI' },
    { name: 'Greece', isoCode: 'GR' },
    { name: 'Greenland', isoCode: 'GL' },
    { name: 'Grenada', isoCode: 'GD' },
    { name: 'Guadeloupe', isoCode: 'GP' },
    { name: 'Guam', isoCode: 'GU' },
    { name: 'Guatemala', isoCode: 'GT' },
    { name: 'Guernsey', isoCode: 'GG' },
    { name: 'Guinea', isoCode: 'GN' },
    { name: 'Guinea-Bissau', isoCode: 'GW' },
    { name: 'Guyana', isoCode: 'GY' },
    { name: 'Haiti', isoCode: 'HT' },
    { name: 'Honduras', isoCode: 'HN' },
    { name: 'Hong Kong', isoCode: 'HK' },
    { name: 'Hungary', isoCode: 'HU' },
    { name: 'Iceland', isoCode: 'IS' },
    { name: 'India', isoCode: 'IN' },
    { name: 'Indonesia', isoCode: 'ID' },
    { name: 'Iran', isoCode: 'IR' },
    { name: 'Iraq', isoCode: 'IQ' },
    { name: 'Ireland', isoCode: 'IE' },
    { name: 'Isle of Man', isoCode: 'IM' },
    { name: 'Israel', isoCode: 'IL' },
    { name: 'Italy', isoCode: 'IT' },
    { name: 'Ivory Coast', isoCode: 'CI' },
    { name: 'Jamaica', isoCode: 'JM' },
    { name: 'Japan', isoCode: 'JP' },
    { name: 'Jersey', isoCode: 'JE' },
    { name: 'Jordan', isoCode: 'JO' },
    { name: 'Kazakhstan', isoCode: 'KZ' },
    { name: 'Kenya', isoCode: 'KE' },
    { name: 'Kiribati', isoCode: 'KI' },
    { name: 'Kosovo', isoCode: 'XK' },
    { name: 'Kuwait', isoCode: 'KW' },
    { name: 'Kyrgyzstan', isoCode: 'KG' },
    { name: 'Laos', isoCode: 'LA' },
    { name: 'Latvia', isoCode: 'LV' },
    { name: 'Lebanon', isoCode: 'LB' },
    { name: 'Lesotho', isoCode: 'LS' },
    { name: 'Liberia', isoCode: 'LR' },
    { name: 'Libya', isoCode: 'LY' },
    { name: 'Liechtenstein', isoCode: 'LI' },
    { name: 'Lithuania', isoCode: 'LT' },
    { name: 'Luxembourg', isoCode: 'LU' },
    { name: 'Macau', isoCode: 'MO' },
    { name: 'Madagascar', isoCode: 'MG' },
    { name: 'Malawi', isoCode: 'MW' },
    { name: 'Malaysia', isoCode: 'MY' },
    { name: 'Maldives', isoCode: 'MV' },
    { name: 'Mali', isoCode: 'ML' },
    { name: 'Malta', isoCode: 'MT' },
    { name: 'Marshall Islands', isoCode: 'MH' },
    { name: 'Martinique', isoCode: 'MQ' },
    { name: 'Mauritania', isoCode: 'MR' },
    { name: 'Mauritius', isoCode: 'MU' },
    { name: 'Mayotte', isoCode: 'YT' },
    { name: 'Mexico', isoCode: 'MX' },
    { name: 'Micronesia', isoCode: 'FM' },
    { name: 'Moldova', isoCode: 'MD' },
    { name: 'Monaco', isoCode: 'MC' },
    { name: 'Mongolia', isoCode: 'MN' },
    { name: 'Montenegro', isoCode: 'ME' },
    { name: 'Montserrat', isoCode: 'MS' },
    { name: 'Morocco', isoCode: 'MA' },
    { name: 'Mozambique', isoCode: 'MZ' },
    { name: 'Myanmar', isoCode: 'MM' },
    { name: 'Namibia', isoCode: 'NA' },
    { name: 'Nauru', isoCode: 'NR' },
    { name: 'Nepal', isoCode: 'NP' },
    { name: 'Netherlands', isoCode: 'NL' },
    { name: 'New Caledonia', isoCode: 'NC' },
    { name: 'New Zealand', isoCode: 'NZ' },
    { name: 'Nicaragua', isoCode: 'NI' },
    { name: 'Niger', isoCode: 'NE' },
    { name: 'Nigeria', isoCode: 'NG' },
    { name: 'Niue', isoCode: 'NU' },
    { name: 'Norfolk Island', isoCode: 'NF' },
    { name: 'North Korea', isoCode: 'KP' },
    { name: 'North Macedonia', isoCode: 'MK' },
    { name: 'Northern Mariana Islands', isoCode: 'MP' },
    { name: 'Norway', isoCode: 'NO' },
    { name: 'Oman', isoCode: 'OM' },
    { name: 'Pakistan', isoCode: 'PK' },
    { name: 'Palau', isoCode: 'PW' },
    { name: 'Palestine', isoCode: 'PS' },
    { name: 'Panama', isoCode: 'PA' },
    { name: 'Papua New Guinea', isoCode: 'PG' },
    { name: 'Paraguay', isoCode: 'PY' },
    { name: 'Peru', isoCode: 'PE' },
    { name: 'Philippines', isoCode: 'PH' },
    { name: 'Pitcairn', isoCode: 'PN' },
    { name: 'Poland', isoCode: 'PL' },
    { name: 'Portugal', isoCode: 'PT' },
    { name: 'Puerto Rico', isoCode: 'PR' },
    { name: 'Qatar', isoCode: 'QA' },
    { name: 'Reunion', isoCode: 'RE' },
    { name: 'Romania', isoCode: 'RO' },
    { name: 'Russia', isoCode: 'RU' },
    { name: 'Rwanda', isoCode: 'RW' },
    { name: 'Saint Barthelemy', isoCode: 'BL' },
    { name: 'Saint Helena', isoCode: 'SH' },
    { name: 'Saint Kitts and Nevis', isoCode: 'KN' },
    { name: 'Saint Lucia', isoCode: 'LC' },
    { name: 'Saint Martin (French part)', isoCode: 'MF' },
    { name: 'Saint Pierre and Miquelon', isoCode: 'PM' },
    { name: 'Saint Vincent and the Grenadines', isoCode: 'VC' },
    { name: 'Samoa', isoCode: 'WS' },
    { name: 'San Marino', isoCode: 'SM' },
    { name: 'Sao Tome and Principe', isoCode: 'ST' },
    { name: 'Saudi Arabia', isoCode: 'SA' },
    { name: 'Senegal', isoCode: 'SN' },
    { name: 'Serbia', isoCode: 'RS' },
    { name: 'Seychelles', isoCode: 'SC' },
    { name: 'Sierra Leone', isoCode: 'SL' },
    { name: 'Singapore', isoCode: 'SG' },
    { name: 'Sint Maarten (Dutch part)', isoCode: 'SX' },
    { name: 'Slovakia', isoCode: 'SK' },
    { name: 'Slovenia', isoCode: 'SI' },
    { name: 'Solomon Islands', isoCode: 'SB' },
    { name: 'Somalia', isoCode: 'SO' },
    { name: 'South Africa', isoCode: 'ZA' },
    { name: 'South Georgia and the South Sandwich Islands', isoCode: 'GS' },
    { name: 'South Korea', isoCode: 'KR' },
    { name: 'South Sudan', isoCode: 'SS' },
    { name: 'Spain', isoCode: 'ES' },
    { name: 'Sri Lanka', isoCode: 'LK' },
    { name: 'Sudan', isoCode: 'SD' },
    { name: 'Suriname', isoCode: 'SR' },
    { name: 'Svalbard and Jan Mayen', isoCode: 'SJ' },
    { name: 'Sweden', isoCode: 'SE' },
    { name: 'Switzerland', isoCode: 'CH' },
    { name: 'Syria', isoCode: 'SY' },
    { name: 'Taiwan', isoCode: 'TW' },
    { name: 'Tajikistan', isoCode: 'TJ' },
    { name: 'Tanzania', isoCode: 'TZ' },
    { name: 'Thailand', isoCode: 'TH' },
    { name: 'Timor-Leste', isoCode: 'TL' },
    { name: 'Togo', isoCode: 'TG' },
    { name: 'Tokelau', isoCode: 'TK' },
    { name: 'Tonga', isoCode: 'TO' },
    { name: 'Trinidad and Tobago', isoCode: 'TT' },
    { name: 'Tunisia', isoCode: 'TN' },
    { name: 'Turkey', isoCode: 'TR' },
    { name: 'Turkmenistan', isoCode: 'TM' },
    { name: 'Turks and Caicos Islands', isoCode: 'TC' },
    { name: 'Tuvalu', isoCode: 'TV' },
    { name: 'U.S. Virgin Islands', isoCode: 'VI' },
    { name: 'Uganda', isoCode: 'UG' },
    { name: 'Ukraine', isoCode: 'UA' },
    { name: 'United Arab Emirates', isoCode: 'AE' },
    { name: 'United Kingdom', isoCode: 'GB' },
    { name: 'United States', isoCode: 'US' },
    { name: 'Uruguay', isoCode: 'UY' },
    { name: 'Uzbekistan', isoCode: 'UZ' },
    { name: 'Vanuatu', isoCode: 'VU' },
    { name: 'Vatican', isoCode: 'VA' },
    { name: 'Venezuela', isoCode: 'VE' },
    { name: 'Vietnam', isoCode: 'VN' },
    { name: 'Wallis and Futuna', isoCode: 'WF' },
    { name: 'Western Sahara', isoCode: 'EH' },
    { name: 'Yemen', isoCode: 'YE' },
    { name: 'Zambia', isoCode: 'ZM' },
    { name: 'Zimbabwe', isoCode: 'ZW' },
  ];

  await prisma.country.createMany({
    data: countriesData, // Renamed variable to avoid conflict
    skipDuplicates: true,
  });
  console.log(`Seeded ${countriesData.length} countries`);

  await prisma.country.createMany({
    data: countriesData,
    skipDuplicates: true,
  });
  console.log(`Seeded ${countriesData.length} countries`);

  console.log('Seeding database with Areas of Law (codes and descriptions only)...');
  const areasOfLawData = [
    // --- General & Foundational ---
    { code: 'CONSTITUTIONAL', description: 'Fundamental principles and structure of the State.' },
    { code: 'HUMAN_RIGHTS', description: 'Fundamental guarantees of individuals.' },
    // --- Public Law ---
    { code: 'ADMINISTRATIVE', description: 'Relations between the State and citizens and functioning of public administration.' },
    { code: 'PENAL', description: 'Crimes and sanctions.' },
    { code: 'PROCEDURAL_GENERAL', description: 'Rules governing judicial procedures.' },
    { code: 'PROCEDURAL_CIVIL', description: 'Procedures in civil and commercial matters.' },
    { code: 'PROCEDURAL_PENAL', description: 'Procedures in criminal matters.' },
    { code: 'TAX', description: 'Taxes, fees and contributions.' },
    // --- Private Law ---
    { code: 'CIVIL', description: 'Relationships between individuals (persons, family, property, inheritance, obligations, contracts).' },
    { code: 'COMMERCIAL', description: 'Commercial acts, business entities, credit instruments.' },
    // --- Social Law ---
    { code: 'LABOR', description: 'Relationships between workers and employers, social security.' },
    { code: 'AGRARIAN_ENVIRONMENTAL', description: 'Regulation of agricultural activity and environmental protection.' },
    { code: 'CHILD_ADOLESCENT', description: 'Organic Law for the Protection of Children and Adolescents.' },
    // --- Specialized Areas ---
    { code: 'INTERNATIONAL_PUBLIC', description: 'Relations between States and other international subjects.' },
    { code: 'INTERNATIONAL_PRIVATE', description: 'Conflicts of laws in international private relationships.' },
    { code: 'INTELLECTUAL_PROPERTY', description: 'Copyright, patents, trademarks.' },
    { code: 'MARITIME', description: 'Regulation of activities at sea.' },
    { code: 'AERONAUTICAL', description: 'Regulation of air navigation.' },
    { code: 'BANKING_FINANCIAL', description: 'Regulation of financial entities and capital markets.' },
    { code: 'INSURANCE', description: 'Insurance contracts and insurance activity.' },
    { code: 'RENTAL_TENANCY', description: 'Regulation of real estate rentals.' },
    { code: 'OTHER', description: 'Other unspecified areas of law.'}
  ];

  // Create each AreaOfLaw and handle potential duplicates by code
  for (const areaData of areasOfLawData) {
    await prisma.areaOfLaw.upsert({
      where: { code: areaData.code }, // Use 'code' for uniqueness check
      update: { description: areaData.description }, // Update description if code exists
      create: { code: areaData.code, description: areaData.description },
    });
  }

  console.log(`Seeded ${areasOfLawData.length} Areas of Law.`);
}

main()
  .catch((e) => {
    console.error('Error during seeding:', e);
    void prisma.$disconnect(); // Ensure disconnection even on error
    process.exit(1);
  })
  .finally(() => {
    console.log('Disconnecting Prisma Client...');
    void prisma.$disconnect(); // Ensure disconnection
  });